version: '3.8'

services:
  scoreboard:
    image: ghcr.io/stayupthetree/mlb_scoreboard:main #change to armv7 for older pi
    container_name: scoreboard
    privileged: true
    devices:
      - /dev/gpiomem:/dev/gpiomem
    volumes:
      - ./config:/app/configs
    environment:
      - WATCHER_ENABLED=true
      - PARAM_LED_GPIO_MAPPING=adafruit-hat-pwm
      - PARAM_LED_BRIGHTNESS=20
      - PARAM_LED_SLOWDOWN_GPIO=4
      - PARAM_LED_COLS=64
      - PARAM_LED_ROWS=32
      - TZ=America/New_York
