version: '3.8'

services:
  scoreboard:
    image: stayupthetree/mlb_scoreboard:armv8
    container_name: scoreboard
    privileged: true
    devices:
      - /dev/gpiomem:/dev/gpiomem
    volumes:
      - ./config.json:/app/config.json
      - ./coordinates:/app/coordinates/
      - ./colors:/app/colors/
    environment:
      - WATCHER_ENABLED=true
      - PARAM_LED_GPIO_MAPPING=adafruit-hat-pwm
      - PARAM_LED_BRIGHTNESS=20
      - PARAM_LED_SLOWDOWN_GPIO=4
      - PARAM_LED_COLS=64
      - PARAM_LED_ROWS=32
      - TZ=America/New_York
